version: '3.18'

services:

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ 'start-dev' ]
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
