package africa.nkwadoma.nkwadoma.domain.enums;

public enum BankName {
    ACCESS_BANK_PLC,
    CITIBANK_NIGERIA_LTD,
    ECO_BANK_NIGERIA_LTD,
    FIDELITY_BANK_PLC,
    FIRST_BANK_OF_NIGERIA_LTD,
    FIRST_CITY_MONUMENT_BANK_PLC,
    GLOBUS_BANK_LTD,
    GUARANTEE_TRUST_BANK_PLC,
    KEYSTONE_BANK_PLC,
    NOVA_COMMERCIAL_BANK_LTD,
    OPTIMUS_BANK,
    PARALLEX_BANK_PLC,
    POLARIS_BANK_PLC,
    PREMIUM_TRUST_BANK,
    PROVIDUS_BANK_LTD,
    SIGNATURE_BANK_LTD,
    STANBIC_IBTC_BANK_PLC,
    STANDARD_CHARTERED_BANK_NIGERIA_LTD,
    STERLING_BANK_PLC,
    SUN_TRUST_BANK_NIGERIA_LTD,
    TITAN_TRUST_BANK_LTD,
    UNION_BANK_0F_NIGERIA_PLC,
    UNITED_BANK_OF_AFRICA_PLC,
    UNITY_BANK_PLC,
    WEMA_BANK_PLC,
    ZENITH_BANK_PLC

}
