package africa.nkwadoma.nkwadoma.domain.enums;

public enum NotificationFlag {
    LOAN_OFFER,
    LOAN_OFFER_DECISION,
    LOAN_REQUEST,
    INVITE_FINANCIER,
    INVESTMENT_VEHICLE,
    APPROVE_INVITE_ORGANIZATION,
    ORGANIZATION_DEACTIVATED,
    ORGANIZATION_REACTIVATED,
    LOAN_DEFERRAL, LOAN_REFERRAL, DROP_OUT,
    LOANEE_DATA_UPLOAD_FAILURE,
    LOANEE_DATA_UPLOAD_SUCCESS,
    REPAYMENT_UPLOAD_SUCCESS,
    REPAYMENT_UPLOAD_FAILURE, ORGANIZATION_INVITATION_REQUESTING_APPROVAL,
    ORGANIZATION_INVITATION_APPROVED,
    ORGANIZATION_INVITATION_DECLINED;

}
