package africa.nkwadoma.nkwadoma.domain.enums;

public enum NotificationFlag {
    LOAN_OFFER,
    LOAN_OFFER_DECISION,
    LOAN_REQUEST,
    INVITE_FINANCIER,
    INVESTMENT_VEHICLE,
    INVITE_ORGANIZATION,
    LOAN_DEFERRAL, LOAN_REFERRAL, DROP_OUT,
    LOAN_USER_DATA,
    REPAYMENT_UPLOAD_FAILURE;
}
