package africa.nkwadoma.nkwadoma.domain.enums;

public enum ServiceOfferingType {
    TRAINING, FINANCIAL_ADVISORY, INSURANCE_SERVICES,
    LOAN_SERVICES, ACCOUNTING_AND_BOOKKEEPING, INVESTMENT_ADVISORY,
    RISK_MANAGEMENT, CORPORATE_FINANCE, TAX_SERVICES,
    BANKING_SERVICES, CRYPTOCURRENCY_SERVICES, SOFTWARE_DEVELOPMENT,
    WEB_DEVELOPMENT, CLOUD_SERVICES, CYBERSECURITY_SERVICES,
    DATABASE_MANAGEMENT, AI_AND_MACHINE_LEARNING, BUSINESS_INTELLIGENCE,
    DEVOPS_SERVICES, BLOCKCHAIN_SERVICES, DISTRIBUTION_SERVICES,
    MARKETING_AND_BRANDING, SALES_SERVICES, CUSTOMER_SERVICE_AND_SUPPORT,
    SUSTAINABILITY_SERVICES, CONSUMER_ENGAGEMENT_AND_LOYALTY,
    TECHNOLOGY_AND_INNOVATION, HOTEL_SERVICES, RESTAURANT_SERVICES,
    EVENT_PLANNING, TRAVEL_AND_TOUR_SERVICES, CORPORATE_RETREATS,
    SPA_AND_WELLNESS, TRANSPORTATION, FILM_AND_TELEVISION,
    MUSIC, THEATRE, SPORTS_AND_FITNESS, GAMING, EVEN_AND_PARTIES,
    TELECOMMUNICATION, PHOTOGRAPHY
}
