# Stage 1: Build
FROM maven:3.8.7 AS build
WORKDIR /app
COPY pom.xml .
#RUN mvn dependency:go-offline -B

COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

ENV SPRING_PROFILES_ACTIVE=dev
ENV SERVER_PORT=8768

EXPOSE 8768

ENTRYPOINT ["sh", "-c", "java -Dserver.port=$SERVER_PORT -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -jar app.jar"]
