ALTER TABLE investment_vehicle_financier_entity_investment_vehicle_designat
DROP CONSTRAINT IF EXISTS fkixcyfka2uaf4ahgox5aq4898b;

DROP TABLE IF EXISTS investment_vehicle_financier_entity_investment_vehicle_designat;