name: Check All Workflows

on:
  workflow_call:
  
  workflow_run:
    workflows: ["Java CI with Maven", "Deploy Systest to Amazon EC2", "Deploy Learnspace Systest to AWS ECS"]  # List all relevant workflows
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check status of workflows
        run: |
          echo "Workflow status: ${{ github.event.workflow_run.conclusion }}"
          # Log the reason if the workflows did not succeed
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflows did not succeed. Status: ${{ github.event.workflow_run.conclusion }}"
          fi
          # Do not exit the script to allow the next job to run
