name: Commit and PR Tracker

on:
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 11 * * *"
    - cron: "0 13 * * *"
    - cron: "0 17 * * *"

jobs:
  check-all-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Check All Workflows Script
        run: |
          chmod +x .github/workflows/scripts/check-all-workflows.sh
          .github/workflows/scripts/check-all-workflows.sh

  track-build:
    needs: check-all-workflows
    runs-on: ubuntu-latest
    if: always()  # Runs regardless of success or failure of the previous job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve Build Tracker Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-tracker
          path: ./build_tracker.json
        continue-on-error: true # Handle missing artifacts without failing the workflow
        
      - name: Initialize or Increment Build Count
        id: build_count
        run: |
          initialize_tracker() {
              echo "Initializing build tracker..."
              echo '{"count": 1, "builds": []}' > ./build_tracker.json
              echo "count=1" >> $GITHUB_ENV
          }
      
          update_tracker() {
              local new_count=$1
              local builds=$2
              local new_build=$3
      
              echo "Updating build tracker..."
              updated_builds=$(jq ".builds += [$new_build]" <<<"$builds")
              echo "{\"count\": $new_count, \"builds\": $updated_builds}" > ./build_tracker.json
          }
      
          if [ -f "./build_tracker.json" ]; then
              count=$(jq '.count' ./build_tracker.json)
              builds=$(jq '.builds' ./build_tracker.json)
              last_timestamp=$(jq -r '.builds[-1].timestamp' ./build_tracker.json)
              new_count=$((count + 1))
          else
              initialize_tracker
              last_timestamp=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
              new_count=1
              builds="[]"
          fi
      
          BUILD_TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          BRANCH="${{ github.head_ref || github.ref_name }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          new_build="{\"branch\":\"$BRANCH\",\"author\":\"$AUTHOR\",\"timestamp\":\"$BUILD_TIMESTAMP\",\"message\":\"$COMMIT_MESSAGE\"}"
      
          update_tracker $new_count "$builds" "$new_build"
      
          TIME_DIFF=$(( ($(date -d "$BUILD_TIMESTAMP" +%s) - $(date -d "$last_timestamp" +%s)) / 3600 ))
      
          echo "count=$new_count" >> $GITHUB_ENV
          echo "builds=$builds" >> $GITHUB_ENV
          echo "timestamp=$BUILD_TIMESTAMP" >> $GITHUB_ENV
          echo "author=$AUTHOR" >> $GITHUB_ENV
          echo "last_timestamp=$last_timestamp" >> $GITHUB_ENV
          echo "time_diff=$TIME_DIFF" >> $GITHUB_ENV

      
      - name: Upload Updated Build Tracker
        uses: actions/upload-artifact@v3
        with:
          name: build-tracker
          path: ./build_tracker.json

      - name: Send Inactivity Email
        if: ${{ env.count == 0 }}
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: 'sam@semicolon.africa,joshua.o@semicolon.africa,ladipo@semicolon.africa,t.lemon@semicolon.africa,divinemercy601@gmail.com,qudusa55@gmail.com,o.koleaje@semicolon.africa,ned@semicolon.africa,tade@semicolon.africa,moyinoluwa@semicolon.africa,mariam@semicolon.africa,i.james@semicolon.africa,david@semicolon.africa,abigail@semicolon.africa,precious@semicolon.africa,dapo@semicolon.africa,pauline@semicolon.africa,davidoso@semicolon.africa,henry@semicolon.africa'
        run: |
          chmod +x .github/workflows/scripts/inactivity_email.sh
          .github/workflows/scripts/inactivity_email.sh \
            "${{ env.SMTP_SERVER }}" "${{ env.SMTP_PORT }}" "${{ env.SMTP_USERNAME }}" \
            "${{ env.SMTP_PASSWORD }}" "${{ env.EMAILS }}" \
            "${{ env.timestamp }}" "${{ env.last_timestamp }}" "${{ env.time_diff }}"

      - name: Send Activity Summary Email
        if: ${{ env.count > 0 }}
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: 'sam@semicolon.africa,joshua.o@semicolon.africa,ladipo@semicolon.africa,t.lemon@semicolon.africa,o.koleaje@semicolon.africa,ned@semicolon.africa,tade@semicolon.africa,moyinoluwa@semicolon.africa,mariam@semicolon.africa,i.james@semicolon.africa,david@semicolon.africa,abigail@semicolon.africa,precious@semicolon.africa,dapo@semicolon.africa,pauline@semicolon.africa,pauline@semicolon.africa,davidoso@semicolon.africa,henry@semicolon.africa'
          BUILDS: ${{ env.builds }}
          LAST_COMMIT_AUTHOR: ${{ env.author }}
          LAST_COMMIT_MESSAGE: $(jq -r '.[-1].message' <<< ${{ env.builds }})
        run: |
          chmod +x .github/workflows/scripts/activity_email.sh
          .github/workflows/scripts/activity_email.sh \
            "${{ env.SMTP_SERVER }}" "${{ env.SMTP_PORT }}" "${{ env.SMTP_USERNAME }}" \
            "${{ env.SMTP_PASSWORD }}" "${{ env.EMAILS }}" \
            "${{ env.timestamp }}" "${{ env.last_timestamp }}" "${{ env.time_diff }}" \
            "${{ env.builds }}" "${{ env.LAST_COMMIT_AUTHOR }}" "${{ env.LAST_COMMIT_MESSAGE }}"
