name: Commit and PR Status Tracker

on:
  pull_request:
    branches:
      - dev
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 17 * * *"
    - cron: "0 14 * * *"
    - cron: "0 23 * * *"


jobs:
  commit-pr-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: 'ladipo@semicolon.africa,sam@semicolon.africa,t.lemon@semicolon.africa,divinemercy601@gmail.com,qudusa55@gmail.com,o.koleaje@semicolon.africa,ned@semicolon.africa,tade@semicolon.africa,moyinoluwa@semicolon.africa,mariam@semicolon.africa,i.james@semicolon.africa,david@semicolon.africa,abigail@semicolon.africa,precious@semicolon.africa,dapo@semicolon.africa,pauline@semicolon.africa,pauline@semicolon.africa,davidoso@semicolon.africa,henry@semicolon.africa '
        run: |
          TIMESTAMP=$(date -u -d "4 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          SUCCESSFUL_COMMITS=$(gh api repos/${{ github.repository }}/commits \
            --paginate -q '.[].commit | select(.verification.verified) | .author.name' \
            --since "$TIMESTAMP" | wc -l)
          SUCCESSFUL_PRS=$(gh api repos/${{ github.repository }}/pulls \
            --paginate -q '.[] | select(.merged_at != null) | .user.login' \
            --state merged --since "$TIMESTAMP" | wc -l)
          echo "SUCCESSFUL_COMMITS=$SUCCESSFUL_COMMITS" >> $GITHUB_ENV
          echo "SUCCESSFUL_PRS=$SUCCESSFUL_PRS" >> $GITHUB_ENV

      - name: Send Inactivity Email
        if: env.SUCCESSFUL_COMMITS == '0' && env.SUCCESSFUL_PRS == '0'
        run: |
          chmod +x .github/workflows/scripts/inactivity_email.sh
          .github/workflows/scripts/inactivity_email.sh \
            "$SMTP_SERVER" "$SMTP_PORT" "$SMTP_USERNAME" \
            "$SMTP_PASSWORD" "$EMAILS"

      - name: Send Activity Summary Email
        if: env.SUCCESSFUL_COMMITS != '0' || env.SUCCESSFUL_PRS != '0'
        run: |
          chmod +x .github/workflows/scripts/activity_email.sh
          .github/workflows/scripts/activity_email.sh \
            "$SMTP_SERVER" "$SMTP_PORT" "$SMTP_USERNAME" \
            "$SMTP_PASSWORD" "$EMAILS" \
            "${{ env.SUCCESSFUL_COMMITS }}" 0 \
            "${{ env.SUCCESSFUL_PRS }}" 0

              --upload-file /tmp/activity_summary.html
          done
