name: Deploy Systest to Amazon EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev    

env:
  REPO_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nkwadoma
  ECR_REPOSITORY: nkwadoma
  AWS_REGION: us-east-1
  CLUSTER: learnspace-africa
  SERVICE: learnspace-backend-systest
  EMAILS: >
    sam@semicolon.africa,joshua.o@semicolon.africa,ladipo@semicolon.africa,
    t.lemon@semicolon.africa,qudusa55@gmail.com,o.koleaje@semicolon.africa,
    ned@semicolon.africa,tade@semicolon.africa,moyinoluwa@semicolon.africa,
    mariam@semicolon.africa,i.james@semicolon.africa,david@semicolon.africa,
    abigail@semicolon.africa,precious@semicolon.africa,dapo@semicolon.africa,
    pauline@semicolon.africa,davidoso@semicolon.africa,henry@semicolon.africa

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the application
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrtes.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: alpha
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and Deploy Docker Container
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          S3_BUCKET_NAME: semicolon-delivery
          S3_REGION: eu-west-1
        run: |
          echo "$EC2_SSH_KEY" > QA-KP.pem
          chmod 600 QA-KP.pem
          ssh -t -o StrictHostKeyChecking=no -i QA-KP.pem $EC2_USER@$EC2_HOST << EOF
          set -e
          echo "SSH connection established!"
          export AWS_REGION="$AWS_REGION"
          export ECR_REGISTRY="$ECR_REGISTRY"

          echo "Authenticating with ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

          echo "Fetching environment variables from S3..."
          aws s3 cp s3://$S3_BUCKET_NAME/nkwadoma/backend/dev/nkwadoma.env nkwadoma-dev.env --region $S3_REGION

          echo "Pulling the latest image..."
          docker pull $ECR_REGISTRY

          echo "Freeing port 8768 if in use..."
          sudo fuser -k 8768/tcp || true

          if [ "$(docker ps -aq -f name=nkwadoma-container)" ]; then
             docker stop nkwadoma-container || true
             docker rm nkwadoma-container || true
          fi

          docker run -d --name nkwadoma-container -p 8768:8768 \
              --env-file nkwadoma-dev.env \
              $ECR_REGISTRY

          docker system prune -af --filter "until=24h" || true
          EOF

  send_notification:
    name: Send Email Notification
    needs: [build-and-push, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set environment variables
        run: |
          PROJECT_NAME="NKWADOMA"
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV
          sanitized_commit_message=$(git log -1 --pretty=%B | tr -d '\n' | tr -d '\r')
          echo "COMMIT_MESSAGE=${sanitized_commit_message}" >> $GITHUB_ENV

      - name: Send build success email notification
        if: success()
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          echo "Sending success email..."
          chmod +x .github/workflows/scripts/send_success_email.sh
          .github/workflows/scripts/send_success_email.sh \
            "$SMTP_SERVER" \
            "$SMTP_PORT" \
            "$SMTP_USERNAME" \
            "$SMTP_PASSWORD" \
            "${{ env.EMAILS }}" \
            "${{ env.TAG }}" \
            "${{ env.BRANCH_NAME }}" \
            "${{ env.COMMIT_AUTHOR }}" \
            "${{ env.COMMIT_MESSAGE }}"

      - name: Send build failure email notification
        if: failure()
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          echo "Sending failure email..."
          chmod +x .github/workflows/scripts/send_failure_email.sh
          .github/workflows/scripts/send_failure_email.sh \
            "$SMTP_SERVER" \
            "$SMTP_PORT" \
            "$SMTP_USERNAME" \
            "$SMTP_PASSWORD" \
            "${{ env.EMAILS }}" \
            "${{ env.TAG }}" \
            "${{ env.BRANCH_NAME }}" \
            "${{ env.COMMIT_AUTHOR }}" \
            "${{ env.COMMIT_MESSAGE }}"
