name: QA Automation Tests
on:
  push:
    branches: [dev]
  # pull_request:
  #   branches: [dev]

jobs:
  run_tests:
    name: Run Automation Tests
    runs-on: ubuntu-latest
    outputs:
      automation_test_url_set: ${{ steps.get_automation_test_url.outputs.automation_test_url_set }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install virtualenv
        run: pip install virtualenv

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Make test script executable
        run: chmod +x test_run_QA.sh

      - name: Run automation tests
        run: ./test_run_QA.sh ${{ secrets.REPO_PAT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: List files for debug
        run: ls -l nkwadoma_backend_QA || true

      # - name: Get Automation Test URL
      #   id: get_automation_test_url
      #   if: always()
      #   run: |
      #     echo "automation_test_url_set=true" >> $GITHUB_OUTPUT

  # deploy-to-local:
  #   name: Deploy to Local Systest
  #   runs-on: self-hosted
  #   needs: build-and-push
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
  #
  #   steps:
  #     - name: Download Environment File
  #       run: |
  #         ENV_FILE_PATH="/home/cloud-group/nkwadoma-systest.env"
  #         aws s3 cp s3://semicolon-delivery/nkwadoma/backend/systest/nkwadoma.env $ENV_FILE_PATH --region eu-west-1
  #
  #     - name: Free Port 8768 If In Use
  #       run: sudo fuser -k 8768/tcp || true
  #
  #     - name: Restart Docker Container
  #       run: |
  #         CONTAINER_NAME=nkwadoma_container
  #         ENV_FILE_PATH="/home/cloud-group/nkwadoma-systest.env"
  #         IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/nkwadoma:alpha
  #
  #         if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
  #           docker stop $CONTAINER_NAME || true
  #           docker rm $CONTAINER_NAME || true
  #         fi
  #
  #         docker network inspect meedl-network >/dev/null 2>&1 || docker network create meedl-network
  #
  #         docker pull $IMAGE_TAG
  #         nohup docker run -d \
  #           --env-file $ENV_FILE_PATH \
  #           --network meedl-network \
  #           --name $CONTAINER_NAME \
  #           -p 8768:8768 \
  #           --restart unless-stopped \
  #           $IMAGE_TAG > /dev/null 2>&1 &
  #
  #     - name: Confirm Deployment Success
  #       run: |
  #         sleep 10
  #         if docker ps --format '{{.Names}}' | grep -q "nkwadoma_container"; then
  #           echo "✅ Deployment to local machine successful!"
  #         else
  #           echo "❌ Deployment failed." && exit 1
