name: Artifact Creation

on:
  push:
    branches:
      - dev  # Adjust as needed
      - trivy-cred-check
  pull_request:
    branches:
      - dev  # Adjust as needed
      - trivy-cred-check

jobs:
  create-build-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Detect Secret Changes
        run: |
          # Path to the previous scan result
          BASELINE_FILE=trivy-baseline-results.txt
      
          # Run Trivy for secrets scanning
          trivy fs --scanners secret --format table > current-secrets-scan.txt
      
          # Compare current scan results with the baseline
          if [ -f "$BASELINE_FILE" ]; then
            echo "Comparing with baseline..."
            if ! diff "$BASELINE_FILE" current-secrets-scan.txt; then
              echo "Secrets have changed! Failing the workflow."
              exit 1
            fi
          else
            echo "No baseline file found. Saving current scan as the new baseline."
          fi
      
          # Save the current scan as the new baseline
          mv current-secrets-scan.txt "$BASELINE_FILE"
      
      - name: Upload Secrets Baseline
        uses: actions/upload-artifact@v3
        with:
          name: trivy-baseline
          path: trivy-baseline-results.txt
      
      - name: Create Build Tracker Artifact
        run: |
          # Initialize or update build tracker file
          BUILD_TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          
          # Prepare the build tracker JSON structure
          if [ ! -f ./build_tracker.json ]; then
            echo '{"count": 1, "builds": [{"timestamp": "'$BUILD_TIMESTAMP'", "author": "'$AUTHOR'", "message": "'$COMMIT_MESSAGE'"}]}' > ./build_tracker.json
          else
            count=$(jq '.count' ./build_tracker.json)
            builds=$(jq '.builds' ./build_tracker.json)
            new_count=$((count + 1))
            new_build="{\"timestamp\":\"$BUILD_TIMESTAMP\",\"author\":\"$AUTHOR\",\"message\":\"$COMMIT_MESSAGE\"}"
            
            # Update the tracker with the new build
            updated_builds=$(echo "$builds" | jq ". += [$new_build]")
            echo "{\"count\": $new_count, \"builds\": $updated_builds}" > ./build_tracker.json
          fi

      - name: Upload Build Tracker Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-tracker
          path: ./build_tracker.json
