name: Artifact Creation

on:
  push:
    branches:
      - dev  # Adjust as needed
  pull_request:
    branches:
      - dev  # Adjust as needed

jobs:
  create-build-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Build Tracker Artifact
        run: |
          # Initialize or update build tracker file
          BUILD_TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          
          # Prepare the build tracker JSON structure
          if [ ! -f ./build_tracker.json ]; then
            echo '{"count": 1, "builds": [{"timestamp": "'$BUILD_TIMESTAMP'", "author": "'$AUTHOR'", "message": "'$COMMIT_MESSAGE'"}]}' > ./build_tracker.json
          else
            count=$(jq '.count' ./build_tracker.json)
            builds=$(jq '.builds' ./build_tracker.json)
            new_count=$((count + 1))
            new_build="{\"timestamp\":\"$BUILD_TIMESTAMP\",\"author\":\"$AUTHOR\",\"message\":\"$COMMIT_MESSAGE\"}"
            
            # Update the tracker with the new build
            updated_builds=$(echo "$builds" | jq ". += [$new_build]")
            echo "{\"count\": $new_count, \"builds\": $updated_builds}" > ./build_tracker.json
          fi

      - name: Upload Build Tracker Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-tracker
          path: ./build_tracker.json
